### ISSUE TITLE
요구사항 및 skillset 정리

### ISSUE THREAD

**Issue by bluewow** [bluewow/newlec-child#5]
게시판 요구사항
- 제목, 내용, 작성자, 날짜를 표시해야한다
- 게시글 생성, 수정, 삭제, 읽을 수 있어야 한다

기타
- 게시판에 집중하기 위해 기타 유저의 회원가입, 로그인은 생략

**Comment by JungHo-1231** [comment]
view는 무엇으로 할까요? 전 타임리프에 한표..

**Comment by bluewow** [comment]
난 mybatis 연습이 필요해서 적용해보려해~

**Comment by bluewow** [comment]
각자 원하는 skill 로 각자 branch 따서 이번 SPRINT 를 진행하는건 어때? 일단 요구사항은 간단하게 적어봤고 추가의견 부탁해~
